name: CI
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
jobs:
  tests:
    name: Run linter and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Lint, eslint and stylelint
        run: yarn lint

      - name: Test build
        run: yarn build
